# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doc_vector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='doc_vector.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x64oc_vector.proto\"#\n\x12\x64oc_vector_request\x12\r\n\x05words\x18\x01 \x03(\t\"\'\n\x10\x64oc_vector_reply\x12\x13\n\x0b\x66\x65\x61ture_vec\x18\x01 \x03(\x01\x32\x44\n\ndoc_vector\x12\x36\n\navg_vector\x12\x13.doc_vector_request\x1a\x11.doc_vector_reply\"\x00\x62\x06proto3')
)




_DOC_VECTOR_REQUEST = _descriptor.Descriptor(
  name='doc_vector_request',
  full_name='doc_vector_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='doc_vector_request.words', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=55,
)


_DOC_VECTOR_REPLY = _descriptor.Descriptor(
  name='doc_vector_reply',
  full_name='doc_vector_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_vec', full_name='doc_vector_reply.feature_vec', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['doc_vector_request'] = _DOC_VECTOR_REQUEST
DESCRIPTOR.message_types_by_name['doc_vector_reply'] = _DOC_VECTOR_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

doc_vector_request = _reflection.GeneratedProtocolMessageType('doc_vector_request', (_message.Message,), dict(
  DESCRIPTOR = _DOC_VECTOR_REQUEST,
  __module__ = 'doc_vector_pb2'
  # @@protoc_insertion_point(class_scope:doc_vector_request)
  ))
_sym_db.RegisterMessage(doc_vector_request)

doc_vector_reply = _reflection.GeneratedProtocolMessageType('doc_vector_reply', (_message.Message,), dict(
  DESCRIPTOR = _DOC_VECTOR_REPLY,
  __module__ = 'doc_vector_pb2'
  # @@protoc_insertion_point(class_scope:doc_vector_reply)
  ))
_sym_db.RegisterMessage(doc_vector_reply)



_DOC_VECTOR = _descriptor.ServiceDescriptor(
  name='doc_vector',
  full_name='doc_vector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=98,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='avg_vector',
    full_name='doc_vector.avg_vector',
    index=0,
    containing_service=None,
    input_type=_DOC_VECTOR_REQUEST,
    output_type=_DOC_VECTOR_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOC_VECTOR)

DESCRIPTOR.services_by_name['doc_vector'] = _DOC_VECTOR

# @@protoc_insertion_point(module_scope)
