# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from doc_vector import doc_vector_pb2 as doc__vector__pb2


class doc_vectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.avg_vector = channel.unary_unary(
        '/doc_vector/avg_vector',
        request_serializer=doc__vector__pb2.doc_vector_request.SerializeToString,
        response_deserializer=doc__vector__pb2.doc_vector_reply.FromString,
        )


class doc_vectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def avg_vector(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_doc_vectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'avg_vector': grpc.unary_unary_rpc_method_handler(
          servicer.avg_vector,
          request_deserializer=doc__vector__pb2.doc_vector_request.FromString,
          response_serializer=doc__vector__pb2.doc_vector_reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'doc_vector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
